---
- name: Install epel repositorio
  yum: name=epel-release state=present

- name: Install MySQL packages dependencies
  yum: name="{{item}}" state=present
  with_items:
      - python-devel
      - gcc
      - python
      - python-pip
      - libselinux-python

#- name: add mysql repository
#  command: rpm -Uvh http://dev.mysql.com/get/mysql-community-release-el7-5.noarch.rpm

#- name: Install MySQL packages 
#  yum: name="{{item}}" state=present
#  with_items:
#      - mysql
#      - mysql-server
#      - mysql-devel
- name: install mariadb and mariadb-server
  yum: name={{ item }} state=present
  with_items:
    - mariadb
    - mariadb-server
    - mariadb-devel

- name: start and enable mariadb
  service: name=mariadb state=started enabled=yes

- name: upgrade pip
  command: pip install --upgrade pip

- name: Install the Python MySQLB module
  pip: name=MySQL-python

- name: deploy /root/.my.cnf
  template: src=root.my.cnf.j2 dest=/root/.my.cnf owner=root group=root mode=0600

- name: Remove the MySQL test database
  action: mysql_db db=test state=absent

#- name: Create global my.cnf
#  template: src=etc.my.cnf dest=/etc/mysql/my.cnf

- name: Create databases
  mysql_db: name={{item}} state=present collation=utf8_general_ci encoding=utf8
  with_items:
      - db1
      - db2

- name: Add deploy DB user and allow access to news_* databases
  mysql_user: name={{user}} password={{password}} host="%" priv=db1.*:ALL/db2.*:ALL,GRANT state=present

- name: Set root password
  mysql_user: name=root password={{password}} host="{{item}}" priv=*.*:ALL,GRANT state=present
  with_items:
      - "{{ansible_hostname}}"
      - 127.0.0.1
      - ::1
      - localhost

- name: Create local my.cnf for root user
  template: src=my.cnf dest=/root/.my.cnf owner=root mode=0600

- name: Restart the MySQL service
  action: service name=mariadb state=restarted enabled=true